### ISSUE TITLE
Suggested API change

### ISSUE THREAD

**Issue by nzakas** [kettanaito/fs-teardown#1]
First off, thanks for creating this. It works exactly how I hoped it would. You've saved me a ton of time.

I wanted to suggest an alternate API that I've found a bit more useful. Rather than passing in multiple arguments for each file and directory, what do you think of something like this?

```js
const { prepare, cleanup, getPath } = createTeardown({

    // specify the root directory
    root: "./foo",

    // specify the empty directories to create
    directories: [
        "bar",
        "baz"
    ],

    // specify the files to create
   files: {
       "foo.txt": "hello world"
   }
});
```

I ended up creating a function that let me pass in this format in my test: https://github.com/eslint/eslint/pull/13709/files#diff-b3f6d058d49aaa6e22207209e60174e9R38

Thanks again!

**Comment by kettanaito** [comment]
Hey, @nzakas. Thank you for the feedback!

You should be able to do this with the present API as well, nesting of a directory structure is optional:

```js
const ROOT_DIR = ‘./root’

const make = (chunks) => {
  return path.resolve(ROOT_DIR, chunks)
}

createTeardown(
  // Directories
  addDirectory(make(‘bar’)),
  addDirectory(make(‘bass’)),
  addDirectory(make(‘nested/dir/too’)),

  // Files
  addFile(make(‘one.txt’)),
  addFile(make(‘two.txt’)),
  addFile(make(‘as/well/as/nested/file.txt’)),
)

**Comment by kettanaito** [comment]
Please, does my suggestion satisfies your use case?

**Comment by nzakas** [comment]
Not quite. It’s still a bit verbose for my use case, so I’m still using my wrapper function.

**Comment by kettanaito** [comment]
I've started the effort to re-design the public API in #6 and the new version will look similar to what you're suggesting. 
I'd be thankful for any kind of feedback on the updated API.

**Comment by kettanaito** [comment]
The public API has been reworked in #6 and now resembles your suggestion. Release pending.
